borderzero/examples

policy-integrations/Dockerfile, policy-integrations/README.md, policy-integrations/app.py, policy-integrations/requirements.txt
=> example for policy-integrations

policy-integrations/app.py
=> few more cleanups

cloudformation-templates/aws_cloudwatch_logs_integration/template.yaml, cloudformation-templates/aws_discovery_integration/template.yaml
Adds example templates to facilitate setting up the 2 aws integrations we support today (cloudwatch logs and discovery)
[ME-1562]: https://mysocket.atlassian.net/browse/ME-1562?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ME-1562] Add AWS Integrations' Sample Templates

cloudformation-templates/aws_connector_installer/template.yaml
AWS CloudFormation template for installing a connector in an AWS VPC/Subnet with a token in AWS SSM.
Fixes:
- https://mysocket.atlassian.net/browse/ME-1593
[ME-1593]: https://mysocket.atlassian.net/browse/ME-1593?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ME-1593] AWS Connector Installation Wizard CFN Template

cloudformation-templates/aws_connector_installer/template.yaml, cloudformation-templates/aws_connector_installer_insecure/template.yaml
=> [HOTFIX] Fix Connector Installer Example Templates

cloudformation-templates/aws_connector_installer/template.yaml
Keeping this up to date with https://github.com/borderzero/border0-cli/pull/238
=> [ME-2115] Handle Connector Token ssm param with slash

kubernetes-templates/connector_in_k8s/connector.yaml
[ME-2407]: https://mysocket.atlassian.net/browse/ME-2407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ME-2407] Update Sample Kubernetes Connector YAML

cloudformation-templates/aws_connector_installer_invite/template.yaml
Connector installation cloudformation template that accepts an invite code and persists/retrieves tokens for the invite code in/from AWS SSM.
[ME-2727]: https://mysocket.atlassian.net/browse/ME-2727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ME-2727] Token Persistence CFN Stack for Connector Install

batch-connector-provisioner/README.md
[ME-2962]: https://mysocket.atlassian.net/browse/ME-2962?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ME-2962] Bulk Provisioner Readme

api-call-examples/README.md, api-call-examples/playground_connector_with_sockets.md, api-call-examples/playground_connector_with_sockets.py, api-call-examples/service_accounts.md, api-call-examples/service_accounts.py
This PR refactors the scripts for managing Border0 connectors, service accounts, and tokens and support for common socket types. The updated README files provide comprehensive usage instructions.
=> ME-3168: Adding service account, tokens, connector and sockets creation scripts

kubernetes-templates/connector_for_k8s_api_sck/connector.yaml
[ME-3230]: https://mysocket.atlassian.net/browse/ME-3230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ME-3230] Add Example Config for K8S API Socket Connector

kubernetes-templates/connector_for_k8s_api_sck/connector.yaml
[[ME-3230](https://mysocket.atlassian.net/browse/ME-3230)] Fix Kubernetes ClusterRole Typo
[ME-3230]: https://mysocket.atlassian.net/browse/ME-3230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ME-3230] Fix Kubernetes ClusterRole Typo

cloudformation-templates/aws_connector_installer/template.yaml, cloudformation-templates/aws_connector_installer_insecure/template.yaml, cloudformation-templates/aws_connector_installer_invite/template.yaml
[ME-3864]: https://mysocket.atlassian.net/browse/ME-3864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ME-3864] Install iptables in Connector CFN Templates

kubernetes-templates/demo_resources/README.md, kubernetes-templates/demo_resources/alpine.yaml, kubernetes-templates/demo_resources/nginx.yaml, kubernetes-templates/demo_resources/ubuntu.yaml
Useful k8s resources for demos, testing out border0, etc.
[ME-4071]: https://mysocket.atlassian.net/browse/ME-4071?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ME-4071] Add Demo K8s Resources Templates

cloudformation-templates/aws_connector_installer/aws-connector-v2-installer.yaml, cloudformation-templates/aws_connector_installer_insecure/aws-connector-v2-installer-insecure.yaml, cloudformation-templates/aws_connector_installer_invite/aws-connector-v2-installer-invite.yaml
SSM start session now uses a different "default" document than before... so we must allow access to that.
[ME-4253]: https://mysocket.atlassian.net/browse/ME-4253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ME-4253] Add New SSM Document to CFN Templates

cloudformation-templates/aws_connector_installer/aws-connector-v2-installer.yaml, cloudformation-templates/aws_connector_installer_insecure/aws-connector-v2-installer-insecure.yaml, cloudformation-templates/aws_connector_installer_invite/aws-connector-v2-installer-invite.yaml
Bug introduced in https://github.com/borderzero/examples/pull/36
[ME-4253]: https://mysocket.atlassian.net/browse/ME-4253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ME-4253] Fix Missing Quote in CFN Templates

cloudformation-templates/aws_connector_installer/aws-connector-v2-installer.yaml, cloudformation-templates/aws_connector_installer_insecure/aws-connector-v2-installer-insecure.yaml, cloudformation-templates/aws_connector_installer_invite/aws-connector-v2-installer-invite.yaml
[ME-4358]: https://mysocket.atlassian.net/browse/ME-4358?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ME-4358] Add IAM Permissions for SSM Exec Support to Connector CFN

cloudformation-templates/aws_connector_installer/aws-connector-v2-installer.yaml, cloudformation-templates/aws_connector_installer_insecure/aws-connector-v2-installer-insecure.yaml, cloudformation-templates/aws_connector_installer_invite/aws-connector-v2-installer-invite.yaml
=> [ME-4394] Fix Bad Substitution in CloudFormation Templates

api-call-examples/expiring_policies/README.md, api-call-examples/session_logs/main.py
Updates to match api changes in https://github.com/mysocketio/api/pull/1726
Fixes # (issue)
- https://mysocket.atlassian.net/browse/ME-4561
[ME-4561]: https://mysocket.atlassian.net/browse/ME-4561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ME-4561] Update Session Log Query Example

kubernetes-templates/connector_for_k8s_api_sck/connector.yaml, kubernetes-templates/connector_in_k8s/connector.yaml
[ME-4568]: https://mysocket.atlassian.net/browse/ME-4568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ME-4568] Add Kubernetes Impersonation Perms
